Resources:
    MessageTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.dynamodbTables.MESSAGE_TABLE_NAME}
            AttributeDefinitions:
                - AttributeName: messageId
                  AttributeType: S
                - AttributeName: message
                  AttributeType: S
                - AttributeName: notified
                  AttributeType: BOOL
                - AttributeName: createdDate
                  AttributeType: S
                - AttributeName: notifiedDate
                  AttributeType: S
            KeySchema:
                - AttributeName: messageId
                  KeyType: HASH
            # Set the capacity to auto-scale
            # BillingMode: PAY_PER_REQUEST
